version: '2'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: --> SET YOUR CUSTOM USER HERE
      POSTGRES_PASSWORD: --> SET YOUR CUSTOM PASSWORD HERE
    ports:
      - "--> SET YOUR EXPOSED PORT HERE:5432"  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080